import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider, CssBaseline } from "@mui/material";
import "./globals.css";
import theme from "../theme";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  preload: true,
  fallback: ['system-ui', 'arial'],
  adjustFontFallback: true,
});

export const metadata: Metadata = {
  title: "AI School",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
  manifest: '/manifest.json',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return <html suppressHydrationWarning className={roboto.variable}>
    <head>
      {/* Preconnect to API to speed up first request */}
      {process.env.NEXT_PUBLIC_DJANGO_API_URL && (
        <link rel="preconnect" href={new URL(process.env.NEXT_PUBLIC_DJANGO_API_URL).origin} />
      )}
    </head>
    <body>
      <InitColorSchemeScript attribute="[data-theme='%s']" />
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
        </ThemeProvider>
      </AppRouterCacheProvider>
    </body>
  </html>
}