export {
  sendAuthRequest,
  sendOauth2Request,
  sendLogoutRequest,
  fetchAuthUser,
  updateAuthUserEmail,
  updateAuthUserPassword,
  deleteAuthUser,
  sendCodeVerificationRequest,
  sendTokenVerificationRequest,
} from "./auth";

export {
  fetchCountryNames,
  fetchRegionNames,
  fetchCityNames,
  fetchCountry,
  fetchHomework,
  sendHomework,
  deleteHomework,
  sendHomeworkPhoto,
  deleteHomeworkPhoto,
  fetchStudentNotes,
  fetchParentNotes,
  fetchTeacherNotes,
  sendNote,
  deleteNote,
  fetchReplacementNames,
  fetchSpecificLesson,
  sendSpecificLesson,
  deleteSpecificLesson,
  fetchSpecificLessonNames,
  sendSpecificLessonPhoto,
  deleteSpecificLessonPhoto,
  fetchAccount,
  sendAccount,
  sendAvatar,
  deleteAvatar,
  fetchPersonDiary,
  fetchPersonHome,
  fetchPersonJournal,
  fetchPersonPermissions,
  unmarkPersonAsAutoCreated,
  fetchProfile,
  sendProfile,
  fetchKlass,
  sendKlass,
  fetchKlassWithLessons,
  sendKlassWithLessons,
  fetchSchool,
  sendSchool,
  sendSchoolPreview,
  deleteSchoolPreview,
  fetchSchools,
  fetchSchoolNames,
  sendSchoolPhoto,
  deleteSchoolPhoto,
  fetchSchoolWithKlasses,
  sendSchoolWithKlasses,
  fetchSchoolWithTimetable,
  sendSchoolWithTimetable,
} from "./diary";

export {
  fetchExams,
  fetchOlympiads,
  fetchManuals,
  fetchManual,
  fetchModule,
  fetchTopic,
  fetchSubjects,
  fetchUserSubjects,
} from "./manuals";

export { isError, handleResponse } from "./errorHandler";
